### PR TITLE
usersitecontrollertests

### PR DESCRIPTION
**Pull request by jkasato**

### CODE REVIEW

**Review by mrobertson-csumb — CHANGES_REQUESTED** [review]
reset AdminSiteControllerMVCTest.java to master's version since I have it complete.

**Review by mrobertson-csumb — CHANGES_REQUESTED** [review]
Changes still not reverted from AdminSiteController
Now pom.xml changes also need to be reverted.

**Review by jkasato — COMMENTED** [review]
removed pom and admin files

**Review by mrobertson-csumb — CHANGES_REQUESTED** [review]
don't delete the files, revert the files to match master
https://stackoverflow.com/a/37972822

**Comment by mrobertson-csumb** [comment]
superseded by `ran maven too`

**Pull request closed without merging**
